// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnoByteLambders.MediTrackSensor.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace TechnoByteLambders.MediTrackSensor.Platform.Shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TechnoByteLambders.MediTrackSensor.Platform.Establishments.Domain.Model.Aggregates.Establishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("EstablishmentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("establishment_name");

                    b.Property<string>("EstablishmentType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("establishment_type");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("p_k_establishments");

                    b.ToTable("establishments");
                });

            modelBuilder.Entity("TechnoByteLambders.MediTrackSensor.Platform.Establishments.Domain.Model.Aggregates.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AlertsAnswered")
                        .HasColumnType("int")
                        .HasColumnName("alerts_answered");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("int")
                        .HasColumnName("establishment_id");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("schedule");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("users_id");

                    b.HasKey("Id")
                        .HasName("p_k_operators");

                    b.HasIndex("EstablishmentId")
                        .HasDatabaseName("i_x_operators_establishment_id");

                    b.ToTable("operators");
                });

            modelBuilder.Entity("TechnoByteLambders.MediTrackSensor.Platform.Iam.Domain.Model.Aggregates.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("entity_code");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("entity_name");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("schedule");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("users_id");

                    b.HasKey("Id")
                        .HasName("p_k_admins");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("TechnoByteLambders.MediTrackSensor.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("job_title");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("photo");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("TechnoByteLambders.MediTrackSensor.Platform.Logistics.Domain.Model.Aggregates.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DoorStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("door_status");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("int")
                        .HasColumnName("establishment_id");

                    b.Property<string>("TypeOfMedication")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type_of_medication");

                    b.Property<string>("TypeOfTransport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type_of_transport");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_transports");

                    b.ToTable("transports");
                });

            modelBuilder.Entity("TechnoByteLambders.MediTrackSensor.Platform.Monitoring.Domain.Model.Aggregates.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DoorStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("door_status");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("int")
                        .HasColumnName("establishment_id");

                    b.Property<string>("ExactLocation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("exact_location");

                    b.Property<string>("TypeOfMedication")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type_of_medication");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_devices");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("TechnoByteLambders.MediTrackSensor.Platform.Subscriptions.Domain.Model.Aggregates.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("plan");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_subscriptions");

                    b.ToTable("subscriptions");
                });

            modelBuilder.Entity("TechnoByteLambders.MediTrackSensor.Platform.Establishments.Domain.Model.Aggregates.Establishment", b =>
                {
                    b.OwnsOne("TechnoByteLambders.MediTrackSensor.Platform.Establishments.Domain.Model.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("EstablishmentId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("CityRegion")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("city_region");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("country");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("district");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("address");

                            b1.HasKey("EstablishmentId")
                                .HasName("p_k_establishments");

                            b1.ToTable("establishments");

                            b1.WithOwner()
                                .HasForeignKey("EstablishmentId")
                                .HasConstraintName("f_k_establishments_establishments_id");
                        });

                    b.OwnsOne("TechnoByteLambders.MediTrackSensor.Platform.Establishments.Domain.Model.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<int>("EstablishmentId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("Latitude")
                                .HasPrecision(10, 8)
                                .HasColumnType("decimal(10,8)")
                                .HasColumnName("latitude");

                            b1.Property<decimal>("Longitude")
                                .HasPrecision(11, 8)
                                .HasColumnType("decimal(11,8)")
                                .HasColumnName("longitude");

                            b1.HasKey("EstablishmentId")
                                .HasName("p_k_establishments");

                            b1.ToTable("establishments");

                            b1.WithOwner()
                                .HasForeignKey("EstablishmentId")
                                .HasConstraintName("f_k_establishments_establishments_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("TechnoByteLambders.MediTrackSensor.Platform.Establishments.Domain.Model.Aggregates.Operator", b =>
                {
                    b.HasOne("TechnoByteLambders.MediTrackSensor.Platform.Establishments.Domain.Model.Aggregates.Establishment", null)
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_operators_establishments_establishment_id");
                });

            modelBuilder.Entity("TechnoByteLambders.MediTrackSensor.Platform.Logistics.Domain.Model.Aggregates.Transport", b =>
                {
                    b.OwnsOne("TechnoByteLambders.MediTrackSensor.Platform.Logistics.Domain.Model.ValueObjects.SensorReading", "SensorReading", b1 =>
                        {
                            b1.Property<int>("TransportId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("AirQuality")
                                .HasPrecision(6, 1)
                                .HasColumnType("decimal(6,1)")
                                .HasColumnName("air_quality");

                            b1.Property<decimal>("AtmosphericPressure")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("atmospheric_pressure");

                            b1.Property<decimal>("Humidity")
                                .HasPrecision(4, 1)
                                .HasColumnType("decimal(4,1)")
                                .HasColumnName("humidity");

                            b1.Property<decimal>("LightIntensity")
                                .HasPrecision(6, 1)
                                .HasColumnType("decimal(6,1)")
                                .HasColumnName("light_intensity");

                            b1.Property<decimal>("SuspendedParticles")
                                .HasPrecision(5, 1)
                                .HasColumnType("decimal(5,1)")
                                .HasColumnName("suspended_particles");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(4, 1)
                                .HasColumnType("decimal(4,1)")
                                .HasColumnName("temperature");

                            b1.Property<decimal>("Vibration")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("vibration");

                            b1.HasKey("TransportId")
                                .HasName("p_k_transports");

                            b1.ToTable("transports");

                            b1.WithOwner()
                                .HasForeignKey("TransportId")
                                .HasConstraintName("f_k_transports_transports_id");
                        });

                    b.Navigation("SensorReading")
                        .IsRequired();
                });

            modelBuilder.Entity("TechnoByteLambders.MediTrackSensor.Platform.Monitoring.Domain.Model.Aggregates.Device", b =>
                {
                    b.OwnsOne("TechnoByteLambders.MediTrackSensor.Platform.Monitoring.Domain.Model.ValueObjects.SensorReading", "SensorReading", b1 =>
                        {
                            b1.Property<int>("DeviceId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("AirQuality")
                                .HasPrecision(6, 1)
                                .HasColumnType("decimal(6,1)")
                                .HasColumnName("air_quality");

                            b1.Property<decimal>("AtmosphericPressure")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("atmospheric_pressure");

                            b1.Property<decimal>("Humidity")
                                .HasPrecision(4, 1)
                                .HasColumnType("decimal(4,1)")
                                .HasColumnName("humidity");

                            b1.Property<decimal>("LightIntensity")
                                .HasPrecision(6, 1)
                                .HasColumnType("decimal(6,1)")
                                .HasColumnName("light_intensity");

                            b1.Property<decimal>("SuspendedParticles")
                                .HasPrecision(5, 1)
                                .HasColumnType("decimal(5,1)")
                                .HasColumnName("suspended_particles");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(4, 1)
                                .HasColumnType("decimal(4,1)")
                                .HasColumnName("temperature");

                            b1.Property<decimal>("Vibration")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("vibration");

                            b1.HasKey("DeviceId")
                                .HasName("p_k_devices");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId")
                                .HasConstraintName("f_k_devices_devices_id");
                        });

                    b.Navigation("SensorReading")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
